// Seed data — AI model profiles
// 텍스트 / 이미지 / 영상 모델 전체 포함

export const MP = {
  // ── Text: OpenAI ──────────────────────────────────────────────────────────
  gpt4o:          'mp_gpt4o',
  gpt4o_mini:     'mp_gpt4o_mini',
  gpt4_1:         'mp_gpt4_1',
  o3_mini:        'mp_o3_mini',
  // ── Text: Anthropic ───────────────────────────────────────────────────────
  claude_sonnet:  'mp_claude_sonnet',   // claude-sonnet-4-6
  claude_opus:    'mp_claude_opus',     // claude-opus-4-7
  claude_haiku:   'mp_claude_haiku',    // claude-haiku-4-5
  // ── Text: Google ──────────────────────────────────────────────────────────
  gemini15:       'mp_gemini_pro',      // backward-compat alias
  gemini_pro:     'mp_gemini_pro',
  gemini_flash:   'mp_gemini_flash',
  // ── Image ─────────────────────────────────────────────────────────────────
  dalle3:         'mp_dalle3',
  imagen3:        'mp_imagen3',
  sd35:           'mp_sd35',
  flux_pro:       'mp_flux_pro',
  ideogram3:      'mp_ideogram3',
  // ── Video ─────────────────────────────────────────────────────────────────
  kling_26:       'mp_kling_26',
  seedance_20:    'mp_seedance_20',
  veo3:           'mp_veo3',
} as const;

export const MODEL_PROFILES_DATA = [
  // ── 텍스트: OpenAI ────────────────────────────────────────────────────────
  {
    id: 'mp_gpt4o',
    profile_name: 'GPT-4o',
    provider_name: 'openai',
    primary_model: 'gpt-4o',
    secondary_model: 'gpt-4o-mini',
    reasoning_depth: 'high',
    creativity_score: 72,
    reliability_score: 88,
    coding_score: 82,
    analysis_score: 88,
    max_budget_per_task: 0.5,
    tool_access_level: 'text',
    active_flag: true,
  },
  {
    id: 'mp_gpt4o_mini',
    profile_name: 'GPT-4o mini',
    provider_name: 'openai',
    primary_model: 'gpt-4o-mini',
    secondary_model: 'gpt-4o',
    reasoning_depth: 'mid',
    creativity_score: 62,
    reliability_score: 82,
    coding_score: 68,
    analysis_score: 72,
    max_budget_per_task: 0.1,
    tool_access_level: 'text',
    active_flag: true,
  },
  {
    id: 'mp_gpt4_1',
    profile_name: 'GPT-4.1',
    provider_name: 'openai',
    primary_model: 'gpt-4.1',
    secondary_model: 'gpt-4o',
    reasoning_depth: 'high',
    creativity_score: 75,
    reliability_score: 90,
    coding_score: 90,
    analysis_score: 90,
    max_budget_per_task: 0.8,
    tool_access_level: 'text',
    active_flag: true,
  },
  {
    id: 'mp_o3_mini',
    profile_name: 'o3-mini (추론형)',
    provider_name: 'openai',
    primary_model: 'o3-mini',
    secondary_model: 'gpt-4o',
    reasoning_depth: 'ultra',
    creativity_score: 55,
    reliability_score: 93,
    coding_score: 95,
    analysis_score: 96,
    max_budget_per_task: 1.0,
    tool_access_level: 'text',
    active_flag: true,
  },
  // ── 텍스트: Anthropic ─────────────────────────────────────────────────────
  {
    id: 'mp_claude_sonnet',
    profile_name: 'Claude Sonnet 4.6',
    provider_name: 'anthropic',
    primary_model: 'claude-sonnet-4-6',
    secondary_model: 'claude-haiku-4-5-20251001',
    reasoning_depth: 'high',
    creativity_score: 86,
    reliability_score: 90,
    coding_score: 93,
    analysis_score: 92,
    max_budget_per_task: 1.0,
    tool_access_level: 'text',
    active_flag: true,
  },
  {
    id: 'mp_claude_opus',
    profile_name: 'Claude Opus 4.7',
    provider_name: 'anthropic',
    primary_model: 'claude-opus-4-7',
    secondary_model: 'claude-sonnet-4-6',
    reasoning_depth: 'ultra',
    creativity_score: 92,
    reliability_score: 93,
    coding_score: 88,
    analysis_score: 97,
    max_budget_per_task: 3.0,
    tool_access_level: 'text',
    active_flag: true,
  },
  {
    id: 'mp_claude_haiku',
    profile_name: 'Claude Haiku 4.5',
    provider_name: 'anthropic',
    primary_model: 'claude-haiku-4-5-20251001',
    secondary_model: 'gpt-4o-mini',
    reasoning_depth: 'low',
    creativity_score: 60,
    reliability_score: 82,
    coding_score: 65,
    analysis_score: 70,
    max_budget_per_task: 0.1,
    tool_access_level: 'text',
    active_flag: true,
  },
  // ── 텍스트: Google ────────────────────────────────────────────────────────
  {
    id: 'mp_gemini_pro',
    profile_name: 'Gemini 1.5 Pro',
    provider_name: 'google',
    primary_model: 'gemini-1.5-pro',
    secondary_model: 'gpt-4o',
    reasoning_depth: 'high',
    creativity_score: 82,
    reliability_score: 85,
    coding_score: 75,
    analysis_score: 88,
    max_budget_per_task: 0.8,
    tool_access_level: 'text',
    active_flag: true,
  },
  {
    id: 'mp_gemini_flash',
    profile_name: 'Gemini 2.0 Flash',
    provider_name: 'google',
    primary_model: 'gemini-2.0-flash',
    secondary_model: 'gpt-4o-mini',
    reasoning_depth: 'mid',
    creativity_score: 78,
    reliability_score: 82,
    coding_score: 72,
    analysis_score: 80,
    max_budget_per_task: 0.2,
    tool_access_level: 'text',
    active_flag: true,
  },
  // ── 이미지 ────────────────────────────────────────────────────────────────
  {
    id: 'mp_dalle3',
    profile_name: 'DALL-E 3 / gpt-image-1',
    provider_name: 'openai-image',
    primary_model: 'gpt-image-1',
    secondary_model: null,
    reasoning_depth: 'mid',
    creativity_score: 88,
    reliability_score: 85,
    coding_score: 0,
    analysis_score: 0,
    max_budget_per_task: 0.1,
    tool_access_level: 'image',
    active_flag: true,
  },
  {
    id: 'mp_imagen3',
    profile_name: 'Google Imagen 3',
    provider_name: 'google-image',
    primary_model: 'imagen-3.0-generate-002',
    secondary_model: null,
    reasoning_depth: 'mid',
    creativity_score: 86,
    reliability_score: 82,
    coding_score: 0,
    analysis_score: 0,
    max_budget_per_task: 0.08,
    tool_access_level: 'image',
    active_flag: true,
  },
  {
    id: 'mp_sd35',
    profile_name: 'Stability AI SD 3.5',
    provider_name: 'stability',
    primary_model: 'sd3.5-large',
    secondary_model: null,
    reasoning_depth: 'mid',
    creativity_score: 90,
    reliability_score: 78,
    coding_score: 0,
    analysis_score: 0,
    max_budget_per_task: 0.08,
    tool_access_level: 'image',
    active_flag: true,
  },
  {
    id: 'mp_flux_pro',
    profile_name: 'fal.ai FLUX Pro',
    provider_name: 'fal',
    primary_model: 'fal-ai/flux-pro',
    secondary_model: null,
    reasoning_depth: 'mid',
    creativity_score: 92,
    reliability_score: 80,
    coding_score: 0,
    analysis_score: 0,
    max_budget_per_task: 0.06,
    tool_access_level: 'image',
    active_flag: true,
  },
  {
    id: 'mp_ideogram3',
    profile_name: 'Ideogram v3',
    provider_name: 'ideogram',
    primary_model: 'V_3',
    secondary_model: null,
    reasoning_depth: 'mid',
    creativity_score: 95,
    reliability_score: 78,
    coding_score: 0,
    analysis_score: 0,
    max_budget_per_task: 0.08,
    tool_access_level: 'image',
    active_flag: true,
  },
  // ── 영상 (KIE.AI) ─────────────────────────────────────────────────────────
  {
    id: 'mp_kling_26',
    profile_name: 'Kling 2.6 — 균형형 ($0.28/5s)',
    provider_name: 'kie.ai',
    primary_model: 'kling-2.6',
    secondary_model: null,
    reasoning_depth: 'low',
    creativity_score: 88,
    reliability_score: 82,
    coding_score: 0,
    analysis_score: 0,
    max_budget_per_task: 0.3,
    tool_access_level: 'video',
    active_flag: true,
  },
  {
    id: 'mp_seedance_20',
    profile_name: 'Seedance 2.0 — 빠른/저가 ($0.25/5s)',
    provider_name: 'kie.ai',
    primary_model: 'seedance-2.0',
    secondary_model: null,
    reasoning_depth: 'low',
    creativity_score: 82,
    reliability_score: 80,
    coding_score: 0,
    analysis_score: 0,
    max_budget_per_task: 0.25,
    tool_access_level: 'video',
    active_flag: true,
  },
  {
    id: 'mp_veo3',
    profile_name: 'Veo 3 — 최고화질 ($0.50/5s)',
    provider_name: 'kie.ai',
    primary_model: 'veo3',
    secondary_model: null,
    reasoning_depth: 'low',
    creativity_score: 95,
    reliability_score: 85,
    coding_score: 0,
    analysis_score: 0,
    max_budget_per_task: 0.5,
    tool_access_level: 'video',
    active_flag: true,
  },
];

export { MODEL_PROFILES_DATA as MODEL_PROFILES };
