// Seed data — LLM model profiles (doc 11 P0 fix #8: MVP routes all to OpenAI)

export const MP = {
  gpt4o:         'mp_gpt4o',
  gpt4o_mini:    'mp_gpt4o_mini',
  claude_sonnet: 'mp_claude_sonnet',
  claude_opus:   'mp_claude_opus',
  claude_haiku:  'mp_claude_haiku',
  gemini15:      'mp_gemini15',
  llama3:        'mp_llama3',
} as const;

export const MODEL_PROFILES = [
  {
    id: MP.gpt4o,
    profile_name: 'GPT-4o',
    provider_name: 'openai',
    primary_model: 'gpt-4o',
    secondary_model: 'gpt-4o-mini',
    reasoning_depth: 'high',
    creativity_score: 70,
    reliability_score: 85,
    coding_score: 80,
    analysis_score: 85,
    max_budget_per_task: 1.0,
    tool_access_level: 'full',
    active_flag: true,
  },
  {
    id: MP.gpt4o_mini,
    profile_name: 'GPT-4o mini',
    provider_name: 'openai',
    primary_model: 'gpt-4o-mini',
    secondary_model: 'gpt-4o',
    reasoning_depth: 'mid',
    creativity_score: 60,
    reliability_score: 80,
    coding_score: 65,
    analysis_score: 70,
    max_budget_per_task: 0.2,
    tool_access_level: 'limited',
    active_flag: true,
  },
  {
    id: MP.claude_sonnet,
    profile_name: 'Claude 3.5 Sonnet',
    provider_name: 'anthropic',
    primary_model: 'claude-3-5-sonnet-20241022',
    secondary_model: 'claude-3-haiku-20240307',
    reasoning_depth: 'high',
    creativity_score: 82,
    reliability_score: 88,
    coding_score: 85,
    analysis_score: 90,
    max_budget_per_task: 1.5,
    tool_access_level: 'full',
    active_flag: true,
  },
  {
    id: MP.claude_opus,
    profile_name: 'Claude 3 Opus',
    provider_name: 'anthropic',
    primary_model: 'claude-3-opus-20240229',
    secondary_model: 'claude-3-5-sonnet-20241022',
    reasoning_depth: 'ultra',
    creativity_score: 90,
    reliability_score: 92,
    coding_score: 82,
    analysis_score: 95,
    max_budget_per_task: 3.0,
    tool_access_level: 'full',
    active_flag: true,
  },
  {
    id: MP.claude_haiku,
    profile_name: 'Claude 3 Haiku',
    provider_name: 'anthropic',
    primary_model: 'claude-3-haiku-20240307',
    secondary_model: 'gpt-4o-mini',
    reasoning_depth: 'low',
    creativity_score: 55,
    reliability_score: 78,
    coding_score: 60,
    analysis_score: 65,
    max_budget_per_task: 0.1,
    tool_access_level: 'limited',
    active_flag: true,
  },
  {
    id: MP.gemini15,
    profile_name: 'Gemini 1.5 Pro',
    provider_name: 'google',
    primary_model: 'gemini-1.5-pro',
    secondary_model: 'gpt-4o',
    reasoning_depth: 'high',
    creativity_score: 85,
    reliability_score: 80,
    coding_score: 75,
    analysis_score: 88,
    max_budget_per_task: 1.0,
    tool_access_level: 'full',
    active_flag: true,
  },
  {
    id: MP.llama3,
    profile_name: 'Llama 3 70B',
    provider_name: 'meta',
    primary_model: 'llama-3-70b-instruct',
    secondary_model: 'gpt-4o-mini',
    reasoning_depth: 'mid',
    creativity_score: 65,
    reliability_score: 72,
    coding_score: 70,
    analysis_score: 72,
    max_budget_per_task: 0.3,
    tool_access_level: 'limited',
    active_flag: true,
  },
];

export { MODEL_PROFILES as MODEL_PROFILES_DATA };
