// Seed data — company, divisions, departments for BLOKS Inc
export const COMPANY_ID = 'company_001';

export const DIV = {
  executive:   'div_exec',
  exec:        'div_exec',
  strategy:    'div_strategy',
  marketing:   'div_marketing',
  research:    'div_research',
  engineering: 'div_engineering',
  operations:  'div_ops',
  ops:         'div_ops',
} as const;

export const DEPT = {
  exec:             'dept_exec',
  strategy:         'dept_strategy',
  product_strategy: 'dept_product_strategy',
  pmo:              'dept_pmo',
  brand:            'dept_brand',
  content:          'dept_content',
  growth:           'dept_growth',
  design:           'dept_design',
  social:           'dept_social',
  analytics:        'dept_analytics',
  market_research:  'dept_market_research',
  investment:       'dept_investment',
  competitive_intel:'dept_competitive_intel',
  data_science:     'dept_data_science',
  strategy_research:'dept_strategy_research',
  backend:          'dept_backend',
  frontend:         'dept_frontend',
  product:          'dept_product',
  qa:               'dept_qa',
  devops:           'dept_devops',
  platform:         'dept_platform',
  security:         'dept_security',
  hr:               'dept_hr',
  admin:            'dept_admin',
  finance:          'dept_finance',
  legal:            'dept_legal',
  operations:       'dept_operations',
} as const;

export const COMPANY = {
  id:          COMPANY_ID,
  name:        'BLOKS Inc',
  code:        'BLOKS',
  world_tone:  'CozyTactical',
  active_flag: true,
};

export const DIVISIONS = [
  { id: DIV.exec,        company_id: COMPANY_ID, name: 'Executive',                division_type: 'Executive',   sort_order: 1, active_flag: true },
  { id: DIV.strategy,    company_id: COMPANY_ID, name: 'Strategy & Planning HQ',   division_type: 'Strategy',    sort_order: 2, active_flag: true },
  { id: DIV.marketing,   company_id: COMPANY_ID, name: 'Marketing & Growth HQ',    division_type: 'Marketing',   sort_order: 3, active_flag: true },
  { id: DIV.research,    company_id: COMPANY_ID, name: 'Research & Investment HQ', division_type: 'Research',    sort_order: 4, active_flag: true },
  { id: DIV.engineering, company_id: COMPANY_ID, name: 'Engineering & Product HQ', division_type: 'Engineering', sort_order: 5, active_flag: true },
  { id: DIV.ops,         company_id: COMPANY_ID, name: 'Platform Operations HQ',   division_type: 'Operations',  sort_order: 6, active_flag: true },
];

export const DEPARTMENTS = [
  { id: DEPT.exec,              division_id: DIV.exec,        name: 'Executive Office',      code: 'exec',             active_flag: true },
  { id: DEPT.strategy,          division_id: DIV.strategy,    name: 'Strategy & Planning',   code: 'strategy',         active_flag: true },
  { id: DEPT.product_strategy,  division_id: DIV.strategy,    name: 'Product Strategy',      code: 'product_strategy', active_flag: true },
  { id: DEPT.pmo,               division_id: DIV.strategy,    name: 'PMO',                   code: 'pmo',              active_flag: true },
  { id: DEPT.brand,             division_id: DIV.marketing,   name: 'Brand',                 code: 'brand',            active_flag: true },
  { id: DEPT.content,           division_id: DIV.marketing,   name: 'Content',               code: 'content',          active_flag: true },
  { id: DEPT.growth,            division_id: DIV.marketing,   name: 'Growth & Performance',  code: 'growth',           active_flag: true },
  { id: DEPT.design,            division_id: DIV.marketing,   name: 'Design',                code: 'design',           active_flag: true },
  { id: DEPT.social,            division_id: DIV.marketing,   name: 'Social Media',          code: 'social',           active_flag: true },
  { id: DEPT.analytics,         division_id: DIV.marketing,   name: 'Analytics',             code: 'analytics',        active_flag: true },
  { id: DEPT.market_research,   division_id: DIV.research,    name: 'Market Research',       code: 'market_research',  active_flag: true },
  { id: DEPT.investment,        division_id: DIV.research,    name: 'Investment Strategy',   code: 'investment',       active_flag: true },
  { id: DEPT.competitive_intel, division_id: DIV.research,    name: 'Competitive Intel',     code: 'competitive_intel',active_flag: true },
  { id: DEPT.data_science,      division_id: DIV.research,    name: 'Data Science',          code: 'data_science',     active_flag: true },
  { id: DEPT.strategy_research, division_id: DIV.research,    name: 'Strategy Research',     code: 'strategy_research',active_flag: true },
  { id: DEPT.backend,           division_id: DIV.engineering, name: 'Backend Engineering',   code: 'backend',          active_flag: true },
  { id: DEPT.frontend,          division_id: DIV.engineering, name: 'Frontend Engineering',  code: 'frontend',         active_flag: true },
  { id: DEPT.product,           division_id: DIV.engineering, name: 'Product & Design',      code: 'product',          active_flag: true },
  { id: DEPT.qa,                division_id: DIV.engineering, name: 'Quality Assurance',     code: 'qa',               active_flag: true },
  { id: DEPT.devops,            division_id: DIV.engineering, name: 'DevOps & Infra',        code: 'devops',           active_flag: true },
  { id: DEPT.platform,          division_id: DIV.ops,         name: 'Platform Operations',   code: 'platform',         active_flag: true },
  { id: DEPT.security,          division_id: DIV.ops,         name: 'Security',              code: 'security',         active_flag: true },
  { id: DEPT.hr,                division_id: DIV.ops,         name: 'HR & People',           code: 'hr',               active_flag: true },
  { id: DEPT.admin,             division_id: DIV.ops,         name: 'Admin & Operations',    code: 'admin',            active_flag: true },
  { id: DEPT.finance,           division_id: DIV.ops,         name: 'Finance',               code: 'finance',          active_flag: true },
  { id: DEPT.legal,             division_id: DIV.ops,         name: 'Legal & Compliance',    code: 'legal',            active_flag: true },
  { id: DEPT.operations,        division_id: DIV.ops,         name: 'Operations',            code: 'operations',       active_flag: true },
];
