// BLOKS roles seed data — all character positions across departments
import { DEPT } from './orgs.js';

export const ROLE = {
  founder: 'role_founder', digital_twin: 'role_digital_twin',
  ceo: 'role_ceo', coo: 'role_coo', cfo: 'role_cfo', cto: 'role_cto', cmo: 'role_cmo',
  strategy_head: 'role_strategy_head', sr_strategist: 'role_sr_strategist',
  ux_planner: 'role_ux_planner', biz_strategist: 'role_biz_strategist',
  pmo_lead: 'role_pmo_lead', ux_analyst: 'role_ux_analyst', spec_writer: 'role_spec_writer',
  mktg_head: 'role_mktg_head', brand_mgr: 'role_brand_mgr', copywriter: 'role_copywriter',
  growth_hacker: 'role_growth_hacker', visual_designer: 'role_visual_designer',
  sns_mgr: 'role_sns_mgr', mktg_analyst: 'role_mktg_analyst',
  research_head: 'role_research_head', market_analyst: 'role_market_analyst',
  competitive_analyst: 'role_competitive_analyst', investment_analyst: 'role_investment_analyst',
  data_scientist: 'role_data_scientist', data_engineer: 'role_data_engineer',
  strategy_researcher: 'role_strategy_researcher',
  eng_head: 'role_eng_head', backend_dev: 'role_backend_dev', frontend_dev: 'role_frontend_dev',
  security_engineer: 'role_security_engineer', product_manager: 'role_product_manager',
  qa_engineer: 'role_qa_engineer', devops_engineer: 'role_devops_engineer',
  junior_dev: 'role_junior_dev', tech_architect: 'role_tech_architect',
  hr_head: 'role_hr_head', ops_manager: 'role_ops_manager',
  finance_analyst: 'role_finance_analyst', legal_compliance: 'role_legal_compliance',
  recruiter: 'role_recruiter', ops_specialist: 'role_ops_specialist',
  strategy_lead: 'role_strategy_lead', product_strategist: 'role_product_strategist',
} as const;

export const ROLES_DATA = [
  { id: 'role_founder',            department_id: DEPT.exec,             name: '창업자 아바타',          family: 'Executive',   is_lead_role: true },
  { id: 'role_digital_twin',       department_id: DEPT.exec,             name: '에코 트윈',              family: 'Executive',   is_lead_role: false },
  { id: 'role_ceo',                department_id: DEPT.exec,             name: 'CEO',                   family: 'Executive',   is_lead_role: true },
  { id: 'role_coo',                department_id: DEPT.exec,             name: 'COO',                   family: 'Executive',   is_lead_role: true },
  { id: 'role_cfo',                department_id: DEPT.exec,             name: 'CFO',                   family: 'Finance',     is_lead_role: true },
  { id: 'role_cto',                department_id: DEPT.exec,             name: 'CTO',                   family: 'Engineering', is_lead_role: true },
  { id: 'role_cmo',                department_id: DEPT.exec,             name: 'CMO',                   family: 'Marketing',   is_lead_role: true },
  { id: 'role_strategy_head',      department_id: DEPT.strategy,         name: '전략기획 본부장',         family: 'Strategy',    is_lead_role: true },
  { id: 'role_sr_strategist',      department_id: DEPT.strategy,         name: '시니어 전략기획',         family: 'Strategy',    is_lead_role: false },
  { id: 'role_ux_planner',         department_id: DEPT.strategy,         name: 'UX 기획 차장',           family: 'Strategy',    is_lead_role: false },
  { id: 'role_biz_strategist',     department_id: DEPT.strategy,         name: '비즈니스 전략 부장',      family: 'Strategy',    is_lead_role: false },
  { id: 'role_pmo_lead',           department_id: DEPT.pmo,              name: 'PMO 리드',               family: 'Strategy',    is_lead_role: true },
  { id: 'role_ux_analyst',         department_id: DEPT.strategy,         name: 'UX 분석 차장',           family: 'Strategy',    is_lead_role: false },
  { id: 'role_spec_writer',        department_id: DEPT.strategy,         name: '스펙 기록 과장',          family: 'Strategy',    is_lead_role: false },
  { id: 'role_mktg_head',          department_id: DEPT.brand,            name: '마케팅 본부장',           family: 'Marketing',   is_lead_role: true },
  { id: 'role_brand_mgr',          department_id: DEPT.brand,            name: '브랜드 부장',             family: 'Marketing',   is_lead_role: false },
  { id: 'role_copywriter',         department_id: DEPT.content,          name: '카피라이터 과장',         family: 'Marketing',   is_lead_role: false },
  { id: 'role_growth_hacker',      department_id: DEPT.growth,           name: '그로스 해커',             family: 'Marketing',   is_lead_role: false },
  { id: 'role_visual_designer',    department_id: DEPT.design,           name: '비주얼 디자이너',         family: 'Design',      is_lead_role: false },
  { id: 'role_sns_mgr',            department_id: DEPT.social,           name: 'SNS 매니저',             family: 'Marketing',   is_lead_role: false },
  { id: 'role_mktg_analyst',       department_id: DEPT.analytics,        name: '마케팅 애널리스트',       family: 'Marketing',   is_lead_role: false },
  { id: 'role_research_head',      department_id: DEPT.market_research,  name: '리서치 본부장',           family: 'Research',    is_lead_role: true },
  { id: 'role_market_analyst',     department_id: DEPT.market_research,  name: '시장 분석 부장',          family: 'Research',    is_lead_role: false },
  { id: 'role_competitive_analyst',department_id: DEPT.competitive_intel,name: '경쟁 분석가',             family: 'Research',    is_lead_role: false },
  { id: 'role_investment_analyst', department_id: DEPT.investment,       name: '투자 분석가',             family: 'Research',    is_lead_role: false },
  { id: 'role_data_scientist',     department_id: DEPT.data_science,     name: '데이터 사이언티스트',     family: 'Data',        is_lead_role: false },
  { id: 'role_data_engineer',      department_id: DEPT.data_science,     name: '데이터 엔지니어',         family: 'Engineering', is_lead_role: false },
  { id: 'role_strategy_researcher',department_id: DEPT.strategy_research,name: '전략 연구원',             family: 'Strategy',    is_lead_role: false },
  { id: 'role_eng_head',           department_id: DEPT.backend,          name: '개발 본부장',             family: 'Engineering', is_lead_role: true },
  { id: 'role_backend_dev',        department_id: DEPT.backend,          name: '백엔드 개발자',           family: 'Engineering', is_lead_role: false },
  { id: 'role_frontend_dev',       department_id: DEPT.frontend,         name: '프론트엔드 개발자',       family: 'Engineering', is_lead_role: false },
  { id: 'role_security_engineer',  department_id: DEPT.security,         name: '보안 엔지니어',           family: 'Security',    is_lead_role: false },
  { id: 'role_product_manager',    department_id: DEPT.product,          name: '프로덕트 매니저',         family: 'Strategy',    is_lead_role: false },
  { id: 'role_qa_engineer',        department_id: DEPT.qa,               name: 'QA 엔지니어',            family: 'Engineering', is_lead_role: false },
  { id: 'role_devops_engineer',    department_id: DEPT.devops,           name: 'DevOps 엔지니어',        family: 'Engineering', is_lead_role: false },
  { id: 'role_junior_dev',         department_id: DEPT.backend,          name: '주니어 개발자',           family: 'Engineering', is_lead_role: false },
  { id: 'role_tech_architect',     department_id: DEPT.platform,         name: '기술 아키텍트',           family: 'Engineering', is_lead_role: false },
  { id: 'role_hr_head',            department_id: DEPT.hr,               name: 'HR 본부장',              family: 'HR',          is_lead_role: true },
  { id: 'role_ops_manager',        department_id: DEPT.admin,            name: '운영 매니저',             family: 'Operations',  is_lead_role: false },
  { id: 'role_finance_analyst',    department_id: DEPT.finance,          name: '재무 분석가',             family: 'Finance',     is_lead_role: false },
  { id: 'role_legal_compliance',   department_id: DEPT.legal,            name: '법무 컴플라이언스',       family: 'Legal',       is_lead_role: false },
  { id: 'role_recruiter',          department_id: DEPT.hr,               name: '리크루터',               family: 'HR',          is_lead_role: false },
  { id: 'role_ops_specialist',     department_id: DEPT.operations,       name: '운영 전문가',             family: 'Operations',  is_lead_role: false },
  { id: 'role_strategy_lead',      department_id: DEPT.strategy,         name: '전략 리드',              family: 'Strategy',    is_lead_role: false },
  { id: 'role_product_strategist', department_id: DEPT.product_strategy, name: '제품 전략가',             family: 'Strategy',    is_lead_role: false },
];
